admin.username=admin
admin.password=admin

# Бэкенд с валидацией (старая версия)
backend.with_validation_fix.url=http://localhost:4110

# Бэкенд с БД (новая версия)
backend.with_database_with_fix.url=http://localhost:4111

# НОВЫЙ бэкенд (с fraud check) - порт 4112
backend.with_fraud_check.url=http://localhost:4112

# Активная версия (можно переопределять через системные свойства)
backend.active.version=with_database_with_fix

apiVersion=/api/v1/

uiRemote=http://localhost:4444/wd/hub
uiBaseUrl=http://192.168.31.215:3000
browser=chrome
browserSize=1920x1080
environment=test

# Database configuration
db.url=jdbc:postgresql://localhost:5433/nbank
db.username=postgres
db.password=postgres
db.driver=org.postgresql.Driver
db.table.customers=customers

# Fraud service configuration (for testing with WireMock)
fraud.service.url=http://localhost:8080